### ISSUE TITLE
CORS on API call

### ISSUE THREAD

**Issue by codehimanshu** [codehimanshu/compiler#1]
CORS error

> Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://api.hackerearth.com/code/compile/. (Reason: CORS header 'Access-Control-Allow-Origin' missing).

user.js:4:3    `url: 'http://api.hackerearth.com/code/compile/'`

**Comment by codehimanshu** [comment]
I get an 500 Internal Server Error on requesting http://localhost/compiler/post.php from ajax.
The URL is correct, I have crosschecked it by opening in browser.
@cmeyer90

**Comment by cmeyer90** [comment]
You may need to install or enable CURL for PHP. Also ensure that your file permissions allow execution of post.php. If you want to check the error output, add the code below to post.php - it will echo errors back as a response to your AJAX request and be visible in the console.

`ini_set('display_errors', 1);
ini_set('display_startup_errors', 1);
error_reporting(E_ALL);
`

**Comment by codehimanshu** [comment]
The issue was that the post.php returned an Error on ajax call. Thnx @cmeyer90  for display error thing.
And thanks @codepoet for the curl.
